/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Vendas;

import DAO.Pessoas.ClienteDAO;
import DAO.Produtos.ProdutoDAO;
import DAO.Vendas.VendaDAO;
import DAO.Vendas.Venda_ProdutoDAO;
import Model.Produtos.Produto;
import Model.Produtos.Venda_Produtos;
import Model.Vendas.Venda;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Leonardo
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVvenda
     */
    public TelaVenda() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tblProdutos.getModel();
        tblProdutos.setRowSorter(new TableRowSorter (model));

        fillTable();
        fillClientes();
        
    }
    
    public void fillTable(){
        DefaultTableModel model = (DefaultTableModel) tblProdutos.getModel();
        model.setNumRows(0);
        ProdutoDAO pDAO = new ProdutoDAO();
        
        for(Produto p: pDAO.readTabelaProduto()){
            model.addRow(new Object[]{
                p.getNome(),
                p.getPreco(),
            });
    }
    }
    
    public void fillClientes(){
        ClienteDAO cDAO = new ClienteDAO();
        List<String> clientes = new ArrayList<>(); 
        clientes = cDAO.readTabelaClienteAtVendas();
        DefaultComboBoxModel comboBoxCliente = new DefaultComboBoxModel(clientes.toArray());
        cmbCliente.setModel(comboBoxCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClientes = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        btnFinaliza = new javax.swing.JButton();
        txtTotalaVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        lblCarrinho = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnExcluiProduto = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblClientes.setText("Cliente");

        btnFinaliza.setText("Finaliza Venda");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        txtTotalaVenda.setEnabled(false);

        jLabel2.setText("R$");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Produto", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setMinWidth(140);
            tblProdutos.getColumnModel().getColumn(0).setPreferredWidth(140);
            tblProdutos.getColumnModel().getColumn(0).setMaxWidth(140);
            tblProdutos.getColumnModel().getColumn(1).setMinWidth(70);
            tblProdutos.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblProdutos.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quant.", "Preco", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCarrinho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCarrinhoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblCarrinho);
        if (tblCarrinho.getColumnModel().getColumnCount() > 0) {
            tblCarrinho.getColumnModel().getColumn(1).setMinWidth(50);
            tblCarrinho.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblCarrinho.getColumnModel().getColumn(1).setMaxWidth(50);
            tblCarrinho.getColumnModel().getColumn(2).setMinWidth(70);
            tblCarrinho.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblCarrinho.getColumnModel().getColumn(2).setMaxWidth(70);
            tblCarrinho.getColumnModel().getColumn(3).setMinWidth(70);
            tblCarrinho.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblCarrinho.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        lblCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCarrinho.setText("Carrinho");

        lblProdutos.setText("Produtos");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade do produto:");

        txtQuantidade.setText("1");

        btnCancelar.setText("Cancelar Venda");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluiProduto.setText("Excluir Produto");
        btnExcluiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiProdutoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClientes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdutos)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluiProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinaliza)
                                .addGap(13, 13, 13))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarrinho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCarrinho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblClientes)
                        .addGap(3, 3, 3)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantidade)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFinaliza)
                        .addComponent(txtTotalaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnExcluiProduto)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        // TODO add your handling code here:
        int numberOfLines = tblCarrinho.getRowCount();
        int line;
        int lineSelected = tblProdutos.getSelectedRow();
        String nome = tblProdutos.getValueAt(lineSelected, 0).toString();
        String produtoExistente;
        Double preco = Double.parseDouble(tblProdutos.getValueAt(lineSelected, 1).toString());
        int quant = Integer.parseInt(txtQuantidade.getText());
        int quantExistente = 0;
        Double total = quant*preco;
        
        DefaultTableModel modelCarrinho = (DefaultTableModel) tblCarrinho.getModel();
        
        
        for(line=0;line<numberOfLines;line++){
            produtoExistente = tblProdutos.getValueAt(line, 0).toString();
            quantExistente = Integer.parseInt(tblCarrinho.getValueAt(line, 1).toString());
            if(produtoExistente.equals(nome)){
                quantExistente += quant; 
                tblCarrinho.setValueAt(quantExistente,line,1);
            }
        }
        
        int result = JOptionPane.showConfirmDialog(null, "Deseja incluir " + quant + "x " + nome + " ao carrinho?",
                "Alerta de inclusao",JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(result == JOptionPane.OK_OPTION){
            addProdutoAtCarrinho(modelCarrinho,nome,quant,preco,total);   
        }
        else{
            JOptionPane.showMessageDialog(null, "O produto não foi adicionado ao carrinho");
        }
        
        calculaTotal();
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void addProdutoAtCarrinho(DefaultTableModel modelCarrinho, String nome, int quant, Double preco, Double total){
        modelCarrinho.addRow(new Object[]{
            nome,
            quant,
            preco,
            total 
            });
    }    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Deseja cancelar essa venda?",
                "Alerta de cancelamento",JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(result == JOptionPane.OK_OPTION){
            cleanTableCarrinho();
             
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    
    private void btnExcluiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiProdutoActionPerformed
        // TODO add your handling code here:

        int line = tblCarrinho.getSelectedRow();
        
        if(line==(-1)){
            JOptionPane.showMessageDialog(null, "Um item tem que estar selecionado para ser exlcuido");
        }
        else
        {
        
        DefaultTableModel model = (DefaultTableModel) tblCarrinho.getModel();
        
        int choice = 0;
        Object[] opcoes = {"Sim", "Nao"};
            choice = JOptionPane.showOptionDialog(null, "Deseja remover esse produto do carrinho?", "Alerta de exclusao", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, 
                    opcoes, opcoes[0]);
            
        switch(choice){
            case 0: 
            model.removeRow(line);
            JOptionPane.showMessageDialog(null, "O produto foi removido");
            break;
                
            case 1: 
            JOptionPane.showMessageDialog(null, "O produto nao foi removido");
            break;
        }
        }
        
        calculaTotal();
    }//GEN-LAST:event_btnExcluiProdutoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaEscolhaParaVenda tela = new TelaEscolhaParaVenda();
        tela.show();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
        // TODO add your handling code here:]
        int numberOfLinesCarrinho = tblCarrinho.getRowCount();
        if(numberOfLinesCarrinho==0){
            JOptionPane.showMessageDialog(null, "Adicione pelo menos um produto no carrinho para fazer uma venda");
        }
        else
        {
            save();
            changeTela();
        }
        
        cleanTableCarrinho();
        
        
    }//GEN-LAST:event_btnFinalizaActionPerformed

    public void changeTela(){
        int choice = 0;
        Object[] opcoes = {"Sim", "Nao"};
            choice = JOptionPane.showOptionDialog(null, "Deseja ir para a tela de vendas ja feitas", "Ir para onde?", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, 
                    opcoes, opcoes[0]);
            
        switch(choice){
            case 0: 
            TelaVendasFeitas telaVenda = new TelaVendasFeitas();
            telaVenda.show();
            this.dispose();
            break;
                
            case 1: 

            break;
        }
    }
    
    public void cleanTableCarrinho(){
        DefaultTableModel model = (DefaultTableModel) tblCarrinho.getModel();
        model.setNumRows(0);
    }

    
    private void tblCarrinhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCarrinhoKeyReleased
        // TODO add your handling code here:
        int lineSelected = tblCarrinho.getSelectedRow();
        Double preco = Double.parseDouble(tblCarrinho.getValueAt(lineSelected, 2).toString());
        int quant = Integer.parseInt(tblCarrinho.getValueAt(lineSelected, 1).toString());
        Double total = quant*preco;
        
        tblCarrinho.setValueAt(total, lineSelected, 3);
        
        calculaTotal();
    }//GEN-LAST:event_tblCarrinhoKeyReleased

    public void calculaTotal(){
        int numberOfLine = tblCarrinho.getRowCount();
        int line;
        double value, totalResult = 0;
        
        for(line=0;line<numberOfLine;line++){
            value = Double.parseDouble(tblCarrinho.getValueAt(line, 3).toString());
            totalResult += value;
        }
        
        txtTotalaVenda.setText(String.valueOf(totalResult));
    }
    
    public void save(){
        saveVenda();
        saveProdutos();
        
    }
    
    public void saveProdutos(){
        int numberOfLines = tblCarrinho.getRowCount();
        int line;
        String nome;
        Double preco;
        int quant;
        
        Venda_ProdutoDAO vpDAO = new Venda_ProdutoDAO();
        List<Venda_Produtos> listVendaProdutos = new ArrayList<>();
        Venda_Produtos vp = new Venda_Produtos();
        
        for(line=0;line<numberOfLines;line++){
            nome = tblCarrinho.getValueAt(line,0).toString();
            preco = Double.parseDouble(String.valueOf(tblCarrinho.getValueAt(line,2)));
            quant = Integer.parseInt(String.valueOf(tblCarrinho.getValueAt(line,1)));
            
            //vp.setId();
            vp.setNome(nome);
            vp.setPreco(preco);
            vp.setQuantidade(quant);
            
            listVendaProdutos.add(vp);
        }
        
        vpDAO.createVendaProdutos(listVendaProdutos);
        
        
        
    }
    
    public void saveVenda(){
        Venda v = new Venda();
        VendaDAO vDAO = new VendaDAO();
        
        String formaPagamento = formaDePagamento();
        int idCliente = cmbCliente.getSelectedIndex()+1;
        Date d = new Date();
        
        try{
            v.setTotalVenda(Double.parseDouble(txtTotalaVenda.getText()));
            v.setDataVenda(d);
            v.setFormaPagamento(formaPagamento);
            v.setCliente(idCliente);
            
        } catch (NumberFormatException ex){}
        
        vDAO.createVenda(v);
        
    }
    
    public String formaDePagamento(){
        String formaPagamento = null;
        Object[] opcoes = { "Pix", "Debito", "Credito", "VA" };
            int formaEscolhida = JOptionPane.showOptionDialog(null, "Qual a forma de pagamento", "Forma de pagamento", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, 
                    opcoes, opcoes[0]);
        switch(formaEscolhida){
            case 0: 
                formaPagamento = "Pix";
            break;
                
            case 1: 
                formaPagamento = "Debito";
            break;
            
            case 2: 
                formaPagamento = "Credito";
            break;
            
            case 3: 
                formaPagamento = "VA";
            break;
        }
        return formaPagamento;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluiProduto;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCarrinho;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTable tblCarrinho;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTotalaVenda;
    // End of variables declaration//GEN-END:variables
}
