/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Vendas;

import View.Vendas.TelaEscolhaParaVenda;
import javax.swing.table.DefaultTableModel;
import DAO.Vendas.VendaDAO;
import Model.Vendas.Venda;

/**
 *
 * @author Leonardo
 */
public class TelaVendasFeitas extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendasFeitas
     */
    public TelaVendasFeitas() {
        initComponents();
        
        fillVendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnExcluirCliente = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Valor Total", "Data", "Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblVendasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblVendas);
        if (tblVendas.getColumnModel().getColumnCount() > 0) {
            tblVendas.getColumnModel().getColumn(0).setMinWidth(50);
            tblVendas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblVendas.getColumnModel().getColumn(0).setMaxWidth(50);
            tblVendas.getColumnModel().getColumn(1).setMinWidth(100);
            tblVendas.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblVendas.getColumnModel().getColumn(1).setMaxWidth(100);
            tblVendas.getColumnModel().getColumn(2).setMinWidth(100);
            tblVendas.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblVendas.getColumnModel().getColumn(2).setMaxWidth(100);
            tblVendas.getColumnModel().getColumn(3).setMinWidth(100);
            tblVendas.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblVendas.getColumnModel().getColumn(3).setMaxWidth(100);
            tblVendas.getColumnModel().getColumn(4).setMinWidth(70);
            tblVendas.getColumnModel().getColumn(4).setPreferredWidth(70);
            tblVendas.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirCliente)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        // TODO add your handling code here:
        int line = tblVendas.getSelectedRow();
        int id = Integer.parseInt(String.valueOf(tblVendas.getValueAt(line, 0)));
        
        VendaDAO vDAO = new VendaDAO();
        
        vDAO.deleteVenda(id);
        
        fillVendas();
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaEscolhaParaVenda tela = new TelaEscolhaParaVenda();
        tela.show();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tblVendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblVendasKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblVendasKeyPressed

    private void fillVendas() {
        DefaultTableModel model = (DefaultTableModel) tblVendas.getModel();
        model.setNumRows(0);
        VendaDAO vDAO = new VendaDAO();
        
        
        for(Venda v: vDAO.readTabelaVenda()){
            model.addRow(new Object[]{
                v.getId(),
                vDAO.clienteForId(v),
                v.getTotalVenda(),
                v.getDataVenda(),
                v.getFormaPagamento()
                
            });
    }  }
    
    public String clienteForId(Venda v){
        Venda venda = new Venda();
        venda = v;
        VendaDAO vDAO = new VendaDAO();
        String nomeCliente;
        nomeCliente = vDAO.clienteForId(venda);
        
        return nomeCliente;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendasFeitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendasFeitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendasFeitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendasFeitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendasFeitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVendas;
    // End of variables declaration//GEN-END:variables

      
}
